### ISSUE TITLE
Question: does this package stay up to date with openai package?

### ISSUE THREAD

**Issue by Mr-Ples** [fcakyon/pywhisper#10]
Greetings,

Not really an issue, just a question. I'm new to github and I'm wondering if this package is now forever separated from the openai/whisper package? In other words do their updates to their repo make it down here to this forked package? If so is it automatic?

Kind regards,
Ples

**Comment by fcakyon** [comment]
I am manually syncing this repo with the openai/whisper. 

You can click on the `openai/whisper` in the readme to see which commit this package is based on: https://github.com/fcakyon/pywhisper#--openaiwhisper--extra-features

At the time of this message, all source from https://github.com/openai/whisper is included + many extra utilities that are not merged into the original repo 👍
